		<p class="main_title">CÁC BỘ TRUYỆN HAY NHẤT</p>
				
				<div class="best_comic">
					<div class="bc_img"><a href="javascript:void(0);" onclick="ReadBook();"><img src="<?php echo $this->imgdir; ?>/post_img.png" alt="" /></a></div>
					<div class="bc_content">
						<p class="bc_c_title"><a href="javascript:void(0);" onclick="ReadBook();">Tên Truyện</a></p>
						<p class="bc_c_info">Tác Giả : xxxxxxxxxx   -   Số Chương : xxxxx   -    Thể Loại : xxxxxxxxxx</p>
						<div class="bc_c_hr"></div>
						<p class="bc_c_description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec risus lectus, nec viverra odio. Ut a diam turpis. Mauris sodales mattis nulla ut feugiat. Maecenas et blandit odio. Ut at pulvinar elit. Nam tristique, tellus rutrum mattis auctor, tortor odio sagittis nunc, eget ultrices purus enim vitae nunc. Donec ultricies massa vel elit feugiat feugiat. Donec auctor dictum auctor....</p>
					</div>
				</div>
				
				<div class="best_comic">
					<div class="bc_img"><a href="javascript:void(0);" onclick="ReadBook();"><img src="<?php echo $this->imgdir; ?>/post_img.png" alt="" /></a></div>
					<div class="bc_content">
						<p class="bc_c_title"><a href="javascript:void(0);" onclick="ReadBook();">Tên Truyện</a></p>
						<p class="bc_c_info">Tác Giả : xxxxxxxxxx   -   Số Chương : xxxxx   -    Thể Loại : xxxxxxxxxx</p>
						<div class="bc_c_hr"></div>
						<p class="bc_c_description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec risus lectus, nec viverra odio. Ut a diam turpis. Mauris sodales mattis nulla ut feugiat. Maecenas et blandit odio. Ut at pulvinar elit. Nam tristique, tellus rutrum mattis auctor, tortor odio sagittis nunc, eget ultrices purus enim vitae nunc. Donec ultricies massa vel elit feugiat feugiat. Donec auctor dictum auctor....</p>
					</div>
				</div>

				<div class="best_comic">
					<div class="bc_img"><a href="javascript:void(0);" onclick="ReadBook();"><img src="<?php echo $this->imgdir; ?>/post_img.png" alt="" /></a></div>
					<div class="bc_content">
						<p class="bc_c_title"><a href="javascript:void(0);" onclick="ReadBook();">Tên Truyện</a></p>
						<p class="bc_c_info">Tác Giả : xxxxxxxxxx   -   Số Chương : xxxxx   -    Thể Loại : xxxxxxxxxx</p>
						<div class="bc_c_hr"></div>
						<p class="bc_c_description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec risus lectus, nec viverra odio. Ut a diam turpis. Mauris sodales mattis nulla ut feugiat. Maecenas et blandit odio. Ut at pulvinar elit. Nam tristique, tellus rutrum mattis auctor, tortor odio sagittis nunc, eget ultrices purus enim vitae nunc. Donec ultricies massa vel elit feugiat feugiat. Donec auctor dictum auctor....</p>
					</div>
				</div>

				<div class="best_comic">
					<div class="bc_img"><a href="javascript:void(0);" onclick="ReadBook();"><img src="<?php echo $this->imgdir; ?>/post_img.png" alt="" /></a></div>
					<div class="bc_content">
						<p class="bc_c_title"><a href="javascript:void(0);" onclick="ReadBook();">Tên Truyện</a></p>
						<p class="bc_c_info">Tác Giả : xxxxxxxxxx   -   Số Chương : xxxxx   -    Thể Loại : xxxxxxxxxx</p>
						<div class="bc_c_hr"></div>
						<p class="bc_c_description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec risus lectus, nec viverra odio. Ut a diam turpis. Mauris sodales mattis nulla ut feugiat. Maecenas et blandit odio. Ut at pulvinar elit. Nam tristique, tellus rutrum mattis auctor, tortor odio sagittis nunc, eget ultrices purus enim vitae nunc. Donec ultricies massa vel elit feugiat feugiat. Donec auctor dictum auctor....</p>
					</div>
				</div>

				<div class="best_comic">
					<div class="bc_img"><a href="javascript:void(0);" onclick="ReadBook();"><img src="<?php echo $this->imgdir; ?>/post_img.png" alt="" /></a></div>
					<div class="bc_content">
						<p class="bc_c_title"><a href="javascript:void(0);" onclick="ReadBook();">Tên Truyện</a></p>
						<p class="bc_c_info">Tác Giả : xxxxxxxxxx   -   Số Chương : xxxxx   -    Thể Loại : xxxxxxxxxx</p>
						<div class="bc_c_hr"></div>
						<p class="bc_c_description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec risus lectus, nec viverra odio. Ut a diam turpis. Mauris sodales mattis nulla ut feugiat. Maecenas et blandit odio. Ut at pulvinar elit. Nam tristique, tellus rutrum mattis auctor, tortor odio sagittis nunc, eget ultrices purus enim vitae nunc. Donec ultricies massa vel elit feugiat feugiat. Donec auctor dictum auctor....</p>
					</div>
				</div>