<?php echo $this->doctype(); ?>   
<html>   
<head> 
	<?php echo $this->headTitle(); ?>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<link href="<?php echo $this->cssdir; ?>/style.css" rel="stylesheet" type="text/css" />
	<script type="text/javascript" src="<?php echo $this->jsdir; ?>/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->jsdir; ?>/jquery-ui.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->jsdir; ?>/captcha_run.js"></script>
	<script type="text/javascript" src="<?php echo $this->jsdir; ?>/tabs_func.js"></script>
	<script type="text/javascript" src="<?php echo $this->jsdir; ?>/tabs_run.js"></script>  
	<script type="text/javascript" src="<?php echo $this->jsdir; ?>/combobox_run.js"></script>  
	<script type="text/javascript" src="<?php echo $this->jsdir; ?>/turn.min.js"></script> 
	
	<?php 
		$auth_login_box = Zend_Auth::getInstance();
	?>
	
</head> 
<body> 
    <div id="wrapper">
		
		<div id="banner">
			<div id="slogan">website slogan</div>
		</div>
		
		<div id="menu">
			<div id="navigation">
				<ul id="navlist">
					<li id="home"><a href="<?php $this->baseUrl();?>/demo/"></a></li>
					<li id="list"><a href="#list.php"></a></li>
					<li id="post"><a  class="active" href="#post.php"></a></li>
					<li id="help"><a href="#help.php"></a></li>
				</ul>
			</div>
			<div id="search_box">
				<form action="index.html" method="POST" name="frm_search">
					<input type="text" id="search_input" name="search_input" value="Nhập từ khoá" onfocus="if (this.value == 'Nhập từ khoá' ) {this.value = '';}" onblur="if (this.value == '' ) {this.value = 'Nhập từ khoá';}" />
					<input type="button" title="button" id="search_button" onclick="frm_search.submit();" />
				</form>
			</div>
		</div>
		
		<div id="new_post">
			<div id="new_post_wrapper">
				<table>
					<tr>
						<td valign="top" align="center">
							<div class="comic_img">
								<a href="javascript:void(0);" onclick="ReadBook();"><img src="<?php echo $this->imgdir; ?>/idemo.png" alt="" /></a>
							</div>
							<div class="comic_info_wrapper">
								<div class="comic_name"><a href="#">Comic Name</a></div>
								<div class="tb_hr"></div>
								<div class="comic_description" >
									Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non diam et lacus pulvinar venenatis et vestibulum velit. Pellentesque interdum faucibus dui.
								</div>
								<div class="tb_hr"></div>
								<div class="comic_chapter">Chapters</div>
								<div class="comic_author">Author</div>
								<div class="comic_category">Category</div>
							</div>
						</td>
						<td valign="top" align="center">
							<div class="comic_img">
								<a href="javascript:void(0);" onclick="ReadBook();"><img src="<?php echo $this->imgdir; ?>/idemo.png" alt="" /></a>
							</div>
							<div class="comic_info_wrapper">
								<div class="comic_name"><a href="#">Comic Name</a></div>
								<div class="tb_hr"></div>
								<div class="comic_description" >
									Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non diam et lacus pulvinar venenatis et vestibulum velit. Pellentesque interdum faucibus dui.
								</div>
								<div class="tb_hr"></div>
								<div class="comic_chapter">Chapters</div>
								<div class="comic_author">Author</div>
								<div class="comic_category">Category</div>/
							</div>
						</td>
						<td valign="top" align="center">
							<div class="comic_img">
								<a href="javascript:void(0);" onclick="ReadBook();"><img src="<?php echo $this->imgdir; ?>/idemo.png" alt="" /></a>
							</div>
							<div class="comic_info_wrapper">
								<div class="comic_name"><a href="#">Comic Name</a></div>
								<div class="tb_hr"></div>
								<div class="comic_description" >
									Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non diam et lacus pulvinar venenatis et vestibulum velit. Pellentesque interdum faucibus dui.
								</div>
								<div class="tb_hr"></div>
								<div class="comic_chapter">Chapters</div>
								<div class="comic_author">Author</div>
								<div class="comic_category">Category</div>
							</div>
						</td>
						<td valign="top" align="center">
							<div class="comic_img">
								<a href="javascript:void(0);" onclick="ReadBook();"><img src="<?php echo $this->imgdir; ?>/idemo.png" alt="" /></a>
							</div>
							<div class="comic_info_wrapper">
								<div class="comic_name"><a href="#">Comic Name</a></div>
								<div class="tb_hr"></div>
								<div class="comic_description" >
									Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non diam et lacus pulvinar venenatis et vestibulum velit. Pellentesque interdum faucibus dui.
								</div>
								<div class="tb_hr"></div>
								<div class="comic_chapter">Chapters</div>
								<div class="comic_author">Author</div>
								<div class="comic_category">Category</div>
							</div>
						</td>
						<td valign="top" align="center">
							<div class="comic_img">
								<a href="javascript:void(0);" onclick="ReadBook();"><img src="<?php echo $this->imgdir; ?>/idemo.png" alt="" /></a>
							</div>
							<div class="comic_info_wrapper">
								<div class="comic_name"><a href="#">Comic Name</a></div>
								<div class="tb_hr"></div>
								<div class="comic_description" >
									Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non diam et lacus pulvinar venenatis et vestibulum velit. Pellentesque interdum faucibus dui.
								</div>
								<div class="tb_hr"></div>
								<div class="comic_chapter">Chapters</div>
								<div class="comic_author">Author</div>
								<div class="comic_category">Category</div>
							</div>
						</td>
					</tr>
				</table>
			</div>
		</div>
		
		<div id="update">
			<div id="update_content">
				Tin tức mới, cập nhật, khuyến mãi,...., consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore....
			</div>
			<div id="update_time_posted">
				about 7 hours ago
			</div>
		</div>
			
		<div id="content">
			<div id="leftcol">
			
				<?php echo $this->layout()->content; ?>

				<p class = "main_title">BANNER QUẢNG CÁO / UPDATE / KHUYẾN MÃI ...</p>
				<span><img src="<?php echo $this->imgdir; ?>/ads1.png" alt="" /></span>
			</div>
			<div id="rightcol">
				<div id="signin_form">
					<?php 
						if(!$auth_login_box->hasIdentity())
						{
					?>
					<div id="sf_top" class="sf_top">
						<p class="sf_lable">Tài Khoản</p>
						<div><input onfocus="if (this.value == 'Administrator' ) {this.value = '';}" type="text" class="signin_text_input" id="signin_username" value="Administrator" /></div>
						<p class="sf_lable">Mật Khẩu</p>
						<div><input type="password" class="signin_text_input" id="signin_password" /></div>
						<div id="wrap_button"><input type="checkbox" id="remember" /> Remember me?&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button id="sf_button" value="" onclick="javascript:SignIn();"></button></div>
						<div id="signin_status">Đăng kí thành viên để tận hưởng những quyền lợi tốt nhất</div>
					</div>
					<div id="sf_bot">
						<div id="sf_bot_left" class="sf_bot_left"><a href="<?php echo $this->baseUrl(); ?>/user/register">Đăng ký ngay</a></div>
						<div id="sf_bot_right" class="sf_bot_right"><a href="<?php echo $this->baseUrl(); ?>/user/lostpassword">Quên tài khoản ?</a></div>
					</div>
					<?php }
						else
						{
					?>
					<div id="sf_top" class="sf_top_logged">
						<p style="font-size: 18px; font-family: tahoma;">Chào: <span style="color: blue; margin-left: 10px;"><?php echo $auth_login_box->getIdentity()->Username;?></span></p>
						<p>Trang thông tin cá nhân</p>
						<p>Truyện yêu thích</p>
						<p>Truyện đã lưu</p>
						<p>Đăng truyện</p>
					</div>
					<div id="sf_bot">
						<div id="sf_bot_left" class="sf_bot_left"><a href="<?php echo $this->baseUrl(); ?>/user/changeinfo">Đổi mật khẩu</a></div>
						<div id="sf_bot_right" class="sf_bot_right"><a href="<?php echo $this->baseUrl(); ?>/user/logout">Đăng xuất</a></div>
					</div>
					<?php 
						}
					?>
				</div>
				<div id="top_post">		
					<ul class="nav">
						<li class="nav-one captain"><a href="#curr_top" class="current">Top Post</a></li>
						<li class="nav-two captain"><a href="#week_top">Tuần</a></li>
						<li class="nav-three captain"><a href="#month_top">Tháng</a></li>
					</ul>
					
					<div class="list-wrap">
						<ul id="curr_top">
							<li><a class="class_for_a" href="#">Top post 1</a></li>
							<li><a class="class_for_a" href="#">Top post 2</a></li>
							<li><a class="class_for_a" href="#">Top post 3</a></li>
							<li><a class="class_for_a" href="#">Top post 4</a></li>
							<li><a class="class_for_a" href="#">Top post 5</a></li>
						</ul>
						 
						 <ul id="week_top" class="hide">
							<li><a class="class_for_a" href="#">Top week 1</a></li>
							<li><a class="class_for_a" href="#">Top week 2</a></li>
							<li><a class="class_for_a" href="#">Top week 3</a></li>
							<li><a class="class_for_a" href="#">Top week 4</a></li>
							<li><a class="class_for_a" href="#">Top week 5</a></li>
						 </ul>
						 
						 <ul id="month_top" class="hide">
							<li><a class="class_for_a" href="#">Top month 1</a></li>
							<li><a class="class_for_a" href="#">Top month 2</a></li>
							<li><a class="class_for_a" href="#">Top month 3</a></li>
							<li><a class="class_for_a" href="#">Top month 4</a></li>
							<li><a class="class_for_a" href="#">Top month 5</a></li>
						 </ul>
					 </div>
				 </div>
				 <div id="tp_page"><a href="#"><</a>&nbsp;&nbsp;&nbsp;<a href="#">1</a>&nbsp;&nbsp;&nbsp;<a href="#">2</a>&nbsp;&nbsp;&nbsp;<a href="#">3</a>&nbsp;&nbsp;&nbsp;<a href="#">4</a> ... <a href="#">9</a>&nbsp;&nbsp;&nbsp;<a href="#">10</a>&nbsp;&nbsp;&nbsp;<a href="#">></a></div>
				<div id="ads_2">
					<div id="ads_2_top">Cộng đồng blogger | infotruyen@gmail.com</div>
					<div id="ads_2_bot"><img src="<?php echo $this->imgdir; ?>/ads_2.png" alt="" /></div>
				</div>
			</div>
		</div>
		
		<div id="top_footer">
			<div id="fintro">
				<p class="ftitle">Giới Thiệu</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec risus lectus, nec viverra odio. Ut a diam turpis. Mauris sodales mattis nulla ut feugiat. Maecenas et blandit odio. Ut at pulvinar elit. Nam tristique, tellus rutrum mattis auctor, tortor odio sagittis nunc, eget ultrices purus enim vitae nunc. Donec ultricies massa vel elit feugiat feugiat. Donec auctor dictum auctor. Morbi et nisl justo, in semper mi. Ut vulputate, orci ac laoreet venenatis, nisl enim suscipit augue, a convallis dolor purus at leo. </p>
			</div>
			<div id="fmenu">
				<p class="ftitle">Menu</p>
				<p><a href="#">Trang Chủ</a></p>
				<div class="f_hr"></div>
				<p><a href="#">List Truyện</a></p>
				<div class="f_hr"></div>
				<p><a href="#">Post Truyện</a></p>
				<div class="f_hr"></div>
				<p><a href="#">Hướng Dẫn</a></p>
			</div>
			<div id="fsocial">
				<p class="ftitle">Mạng Xã Hội</p>
				<div>
					<a href="https://twitter.com/"><img src="<?php echo $this->imgdir; ?>/twister.png" alt="" /></a>
					<a href="http://www.flickr.com/"><img src="<?php echo $this->imgdir; ?>/flickr.png" alt="" /></a>
					<a href="http://facebook.com/"><img src="<?php echo $this->imgdir; ?>/face.png" alt="" /></a>
					<a href="http://dribbble.com/"><img src="<?php echo $this->imgdir; ?>/dribbble.png" alt="" /></a>
					<a href="http://delicious.com/"><img src="<?php echo $this->imgdir; ?>/delicous.png" alt="" /></a>
					<a href="https://plus.google.com/"><img src="<?php echo $this->imgdir; ?>/plus.png" alt="" /></a>
				</div>
				<p class="ftitle">Liên Hệ</p>
				<p>129/6 Nguyễn Trãi, Phường 2, Quận 5, TP. HCM</p>
				<p>+(083) 923 5684</p>
				<p>info@gudss.com</p>
			</div>
		</div>

		<div id="bot_footer">
			<div id="copyright">
				<p>Good Service Seeking Company © All rights reserved</p>
			</div>
			<div id="counter">Lượt truy cập: xxxxxxxxxxxxxxx</div>
		</div>
	</div>
	
	<div class="wrap-flipbook">
		<div class="close-bf" onclick="javascript:HideBook();"></div>
		<div class="next-icon" onclick="$('#book').turn('next')"></div>
		<div class="prev-icon" onclick="$('#book').turn('previous')"></div>
		
		
		<!-- Begin book -->
		
		<div id="book">
			<div class="p1 cover odd hard"></div>
			<div class="p2 hard"></div>
			<div class="p3 odd own-size"></div>
			<div class="p4 even own-size"></div>
			<div class="p5 odd own-size">
				<div class="table-contents">
					<h1>Contents</h1>
					<ul>
						<li><a href="#7">The book <span>7</span></a></li>
						<li><a href="#10">Youth<span>10</span></a></li>
						<li><a href="#18">The Apple I <span>18</span></a></li>
						<li><a href="#25">Apple's early days <span>25</span></a></li>
						<li><a href="#30">Success and failures <span>30</span></a></li>
						<li><a href="#40">Leaving Apple  <span>40</span></a></li>
						<li><a href="#43">NeXT Inc <span>43</span></a></li>
						<li><a href="#53">Wildreness years <span>53</span></a></li>
						<li><a href="#73">A visionary <span>73</span></a></li>
						<li><a href="#86">Apple is strong <span>86</span></a></li>
						<li><a href="#97">2010: Steve is back<span>97</span></a></li>
					</ul>
				</div>
				<span class="page-number">5</span>
			</div>

			<div class="p6 even own-size">
				
			</div>

			<div class="p7 odd own-size">
				<div class="book-content">

					<h1>The Book</h1>

					<p class="capital">
					Steve Jobs is the authorized biography of Steve Jobs. The biography was written at the request of Jobs by acclaimed biographer Walter Isaacson, a former executive at CNN and Time who has written best-selling biographies about Benjamin Franklin and Albert Einstein.
					</p>

					<p>
					Based on more than forty interviews with Jobs conducted over two years—in addition to interviews with more than one hundred family members, friends, adversaries, competitors, and colleagues—Isaacson was given "exclusive and unprecedented" access to Jobs's life. Jobs is said to have encouraged the people interviewed to speak honestly. Although Jobs cooperated with the book, he asked for no control over its content other than the book's cover, and waived the right to read it before it was published.
					</p>

					</div>
					<span class="page-number">7</span>
			</div>
			<div class="p8 even own-size">
				<div class="book-content">
				<p>
				The book is described as "[chronicling] the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries: personal computers, animated movies, music, phones, tablet computing, and digital publishing."
				</p>

				<p>
				In just over 600 pages, the book covers Jobs' entire life, from his childhood in his adoptive parents' home in California to his three bouts with pancreatic cancer. Early chapters include one on his relationship with Steve Wozniak and Jobs' brief stint at Hewlett-Packard, Reed College, Atari, and a formative trip to India to find himself. A chapter each is devoted to the development of the Apple I, Apple II, Lisa, and the classic Macintosh during his early years, the founding of NeXT and funding of Pixar when he was ousted from Apple, and Jobs' triumphant and incredibly productive return to Apple starting in 1997. Following the latter "second coming" of Jobs, Isaacson chronicles the development
				</p>
				</div>
				<span class="page-number">8</span>
			</div>
			<div class="p9 odd own-size">
				<div class="book-content">

					<p class="center-pic">
						<img src="<?php echo $this->imgdir; ?>/book/books.jpg" style="width:350px; height:230px;">
					</p>

					<p class="no-indent">
					of the iMac, iPod, iTunes, Apple Stores, and iPad.
					</p>


					<p>
					Jobs' abrasive personality, which simultaneously inspired and intimidated those around him, is a recurrent theme throughout. Details of his personal life are also included, including early relationships, his marriage of twenty years, and his four children and his early life. 

				</div>
				<span class="page-number">9</span>
			</div>
			<div class="p10 even own-size">
				<div class="book-content">

					<h1>Youth</h1>

					<h2>The jobs family</h2>

					<p class="capital">
					Steve Jobs was born on February 24, 1955, in the city of San Francisco. His biological mother was an unwed graduate student named Joanne Simpson,
					and his biological father was either a political science or mathematics professor, a native Syrian named Abdulfattah John Jandali.
					</p>


					<p>
					Being born out of wedlock in the puritan America of the 1950s, the baby
					was put up for adoption. Joanne had a college education, and she insisted that the future parents of her boy be just as well educated. Unfortunately,
					the candidates, Paul and Clara Jobs, did not meet her expectations: they were a lower-middle class couple that had settled in the Bay Area after the
					war. Paul was a machinist from the Midwest who had
					</p>


					</div>
					<span class="page-number">10</span>
			
			</div>
			<div class="p11 odd own-size">
				<div class="book-content">

					<p class="no-indent">
					not even graduated from high school. In the end, Joanne agreed to have her baby adopted by
					them, under the firm condition that they later send him to college.
					</p>

					<p>
					Paul and Clara called their new son Steven Paul. While Steve was still a toddler, the couple moved to the Santa Clara county, later to be known as
					Silicon Valley. They adopted another baby, a girl called Patti, three years later in 1958.
					</p>

					<h2>Childhood</h2>

					<p> 
					<img class="left-pic zoom-this" src="<?php echo $this->imgdir; ?>/book/young.jpg" width="100" height="113">Steve was quite a turbulent child. He really didn’t care about school for
					some time — until he reached the 4th grade, and had Imogene “Teddy” Hill as a teacher.</p>

					<p>She did bribe him, with candy and $5 bills from her own money. He quickly became hooked — so</p>

					</div>
					<span class="page-number">11</span>
			</div>
			<div class="p12 even own-size">
				<div class="book-content">

					<p class="no-indent">
					much so that he skipped the 5th grade and went straight to middle school, namely Crittenden Middle School. It was in a poor area. Most kids did not work much there, they were rather fond of bullying other kids, such as the young Steve. One day he came home and declared that if he wasn’t transferred to another school, he would stop going to school altogether. He was 11. Paul and Clara complied, and the Jobses moved to the cozier city of Los Altos, so that Steve could go to Cupertino Junior High. This proved to be decisive for Steve’s future.
					</p>

					<p>
					As Steve was growing up in Los Altos, he became increasingly curious about the world of electronics that filled his neighbors’ garages. His own
					father introduced him to Heathkits, which fascinated him.
					</p>

					<h2>Homestead High</h2>

					<p>
					When Steve arrived in Homestead High School, he enrolled in a popular electronics class. His teacher was
					</p>

					</div>
					<span class="page-number">12</span>
			</div>
			<div class="p13 odd own-size">
				<div class="book-content">

					<p class="no-indent">
					Mr. McCollum. McCollum later recalled of one time when his pupil Steve called up David Hewlett himself, co-founder of HP, to get spare parts for his homework, and even a summer job at HP’s factory. Steve’s entrepreneurial skills showed up early in his life indeed.
					</p>

					<p>

					<img class="left-pic zoom-this" src="<?php echo $this->imgdir; ?>/book/highschool.jpg" width="172" height="159">
					At Homestead, Steve befriended Bill Fernandez, a neighbor who shared his interests in electronics. It was Bill who first introduced him to another computer whiz kid, an older guy named Stephen Wozniak, or — as everybody used to call him — Woz. Steve and Woz met in 1969, when they were respectively 14 and 19. At the time, Woz was building a little computer board with Bill Fernandez that they called “the Cream Soda Computer”.</p>

					</div>
					<span class="page-number">13</span>
			</div>
			<div class="p14 even own-size">
				<div class="book-content">

					<blockquote>
					Typically, it was really hard for me to explain to people the kind of design stuff I worked on, but Steve got it right away. And I liked him. He was kind of skinny and wiry and full of energy. [...] Steve and I got close right away, even though he was still in high school [...]. We talked electronics, we talked about music we liked, and we traded stories about pranks we’d pulled.
					</blockquote>

					<cite>Steve Wozniak in iWoz</cite>

					<p>
					Woz and Steve later engaged in several pranks together, including putting a
					huge middle finger on one of the high school’s building.
					</p>

					<p>
					It was also at Homestead that Steve met Chris-Ann Brennan, his first steady girlfriend, with whom he stayed for several years. A couple of years later, Woz and Steve started their first entrepreneurial venture. It was 1972, and on US campuses, there was a lot of talk about “phone phreaks.” They were early computer
					</p>

					</div>
					<span class="page-number">14</span>
			</div>
			<div class="p15 odd own-size">
				<div class="book-content">

					<p class="no-indent">
					 hackers that managed to build “blue boxes” — little devices that fooled AT&T’s long-distance switching equipment, and allowed you to make phone calls for free.
					</p>

					<p>

					Woz read about them in an article which he showed to Steve. 
					<img class="left-pic zoom-this" src="<?php echo $this->imgdir; ?>/book/highschool2.jpg" width="172" height="214">
					They both tried to build one, and to their surprise, it worked! It was Steve who came up with the idea of selling them; he and Woz would go from room to room in Berkeley’s dorms, where Woz was a student, and sell them to interested students. However, this business was illegal and the two of them stopped after they almost got caught by the police.
					</p>

					</div>
					<span class="page-number">15</span>
			</div>
			<div class="p16 even own-size">
				<div class="book-content">

					<h2>Reed College</h2>
					<p>
					The following year, Steve finished high school and reached college age. He decided to go to the fancy Reed College, a private liberal arts college up in Oregon. However, the tuition for Reed was so expensive that Paul and Clara could hardly afford it. Yet they were bound by the promise they’d make to their son’s biological mother, so they spent almost their entire life’s savings on their son’s higher education.
					</p>

					<p>
					Steve only officially stayed for a couple of months at Reed. He dropped out before Christmas. However, that allowed him to “drop in” on classes he was not supposed to attend.
					</p>

					<p>
					It was at Reed that Steve started experimenting with Eastern mysticism. He delved into weird books and came to believe that if he ate only fruits, for example, he would eliminate all mucus and not need to shower
					</p>


					</div>
					<span class="page-number">16</span>
			</div>
			<div class="p17 odd own-size">
				<div class="book-content">


					<p class="no-indent">
					anymore. He also started his habit of fasting for long periods of time (he would still do so ten years later, when he was a multi-millionaire). He occasionally used LSD, and became something of a laggard hippie. One of his best friends at Reed was Dan Kottke, who shared his interests in such philosophies.
					</p>

					<p>
					<img class="left-pic zoom-this" src="<?php echo $this->imgdir; ?>/book/collegue.jpg" width="172" height="129">
					The following year, in 1974, Steve desperately needed money, so he got a job at Atari. Atari was arguably the first video game company: it was created by Nolan Bushnell in 1972, and one of its ␣rst employees was Al Acorn, the inventor of Pong. Steve was hired although he would often call his co-workers names and smell pretty bad. That’s why he was soon moved to the night shift.
					</p>


					</div>
					<span class="page-number">17</span>
			</div>
			<div class="p18 even own-size">
				<div class="book-content">


					<h1>The Apple I</h1>


					<h2>Homebrew</h2>



					<p class="capital">
					While Steve had been away in India or Oregon, his geek friend Woz had
					been hired by Hewlett-Packard. To him, it was a dream job: a company full of passionate engineers just like him, where he could work on products for
					other engineers. However, in his spare time, he had cultivated his interest in designing computer circuits, and had joined a computer hobbyists
					association called the Homebrew Computer Club.
					</p>



					<p>

					Woz was impressed by the Altair (and by Microsoft’s BASIC interpreter), but
					he knew from his almost life-long experience in circuit design that he could do a much better job. So he started work on his own computer — which he
					decided to base on another
					</p>
					</div>
					<span class="page-number">18</span>
			</div>
			<div class="hard fixed p19"></div>
			<div class="p20 hard"></div>
		</div>
		
		<!-- End book -->
		
		
	</div>
	
	
	<script type="text/javascript">
		var str = null;
		function changeRegBox(succ_username)
		{
			$('#sf_top').html('<p style="font-size: 18px; font-family: tahoma;">Chào: <span style="color: blue; margin-left: 10px;">'+succ_username+'</span></p><p>Trang thông tin cá nhân</p><p>Truyện yêu thích</p><p>Truyện đã lưu</p><p><a href="#">Đăng truyện</a></p>');
			$('#sf_top').removeClass().addClass('sf_top_logged');
			$('#sf_bot_left').html('<a href="<?php echo $this->baseUrl(); ?>/user/changeinfo">Đổi mật khẩu</a>');
			$('#sf_bot_right').html('<a href="<?php echo $this->baseUrl(); ?>/user/logout">Đăng xuất</a>');
		}
		function PostBackSignin(source){
			$.ajax({
				url:"/ts24h/user/login",
				type:"POST",
				async:false,
				data:source,
				success:function(result){
					str = result;
				},
				error:function(){
					alert("Lỗi kết nối!");
				}
			});
			return str;
		}
		function SignIn()
		{
			$('#signin_status').html('<img src="<?php echo $this->imgdir; ?>/loading.gif" alt="" />');
			var login_result = PostBackSignin('username='+$('#signin_username').val()+'&password='+$('#signin_password').val()+'&login_postback=1');
			if(login_result == 0)
			{
				$('#signin_status').css('color', 'red');
				$('#signin_status').html('Tên đăng nhập hoặc mật khẩu không đúng.');
			}
			else
			{
				changeRegBox(login_result);
			}
		}
	</script>
	
	<script type="text/javascript" src="http://api.recaptcha.net/challenge?k=6LfyetQSAAAAAGsmGBMAmCCtoEfXdPRksEnnFFwf"></script>
	<script type="text/javascript">
		function ReadBook()
		{
			$("#book").css("visibility","visible");
			$(".wrap-flipbook").css("visibility","visible");
			$("#book").turn({
				autoCenter: true,
				width: 960,
				height: 600,
				when: {
					turning: function(e, page, view){
						
						if (page>=2)
							$('.p2').addClass('fixed');
						else
							$('.p2').removeClass('fixed');
	
						if (page<20)
							$('.p19').addClass('fixed');
						else
							$('.p19').removeClass('fixed');
					}
				}
			});
		}
		function HideBook()
		{
			window.location = window.location.href;
		}
	</script>
</body> 
</html>
