<p><a href="<?php echo $this->root; ?>/user/register/">Đăng ký</a></p>
<p><a href="<?php echo $this->root; ?>/user/login/">Đăng nhập (COMMING SOON)</a></p>
<p><a href="<?php echo $this->root; ?>/user/logout/">Đăng xuất (COMMING SOON)</a></p>
<p><a href="<?php echo $this->root; ?>/user/lostpassword/">Tìm lại mật khẩu (COMMING SOON)</a></p>
<p><a href="<?php echo $this->root; ?>/user/changeinfo/">Thay đổi mật khẩu / email (COMMING SOON)</a></p>
<p><a href="<?php echo $this->root; ?>/user/addfavorite/">Lưu truyện yêu thích (COMMING SOON)</a></p>

