			<?php if($this->show_content) {?>
			<p class = "main_title">QUÊN MẬT KHẨU (NOT COMPLETE)</p>
				<div id="forgot_pass_wrap">
					<div id="forgot_pass">
						<p id="fp_label">Email đăng ký</p>
						<div><input type="text" id="fp_txt" name="username" /></div>
						
						<div class="captcha_wrap">
							<div class="capt_info">
								<div class="capt_img" id="recaptcha_image"></div>
								<div class="capt_right">
									<div class="capt_mini_btn"><a href="javascript:Recaptcha.switch_type('image');"><img src="<?php echo $this->imgdir; ?>/captcha/c_reload.png" alt="" /></a></div>
									<div class="capt_mini_btn"><a href="javascript:Recaptcha.switch_type('audio');"><img src="<?php echo $this->imgdir; ?>/captcha/c_audio.png" alt="" /></a></div>
									<div ><img src="<?php echo $this->imgdir; ?>/captcha/c_ques.png" alt="" /></div>
								</div>
							</div>
							<div class="capt_input_wrap">
								<input class="capt_input" type="text" id="recaptcha_response_field" name="recaptcha_response_field" />
							</div>
						</div>

						<div><input type="submit" value="" id="fp_btn" /></div>
					</div>
				</div>
				<script type='text/javascript'>
					var str = "";
					function PostBack(source){
						$.ajax({
							url:"<?php echo $this->url(); ?>",
							type:"POST",
							async:false,
							data:source,
							success:function(result){
								str = result;
							},
							error:function(){
								alert("Lỗi kết nối.");
							}
						});
						return str;
					}
						
				</script>
				<?php } ?>